---
name: Build and Push Python monitoring application to Google Cloud Platform
on: 
  push:
    branches:
      - main


jobs:
  # example with Workload Identity Federation
  build-and-push-to-gcr:
    name: Build & push to GCP
    runs-on: ubuntu-latest
    permissions: #make sure we add permission to read and write package
      contents: read
      packages: write
    env:        #variables
        IMAGE_NAME: PythonMonitoringApp
        PROJECT_ID: focal-future-307712
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to GCR
      uses: google-github-actions/auth@v2 #checkouts GCR repo, so this workflow can access it
      with:
        workload_identity_provider: https://iam.googleapis.com/projects/766703756158/locations/global/workloadIdentityPools/123a/providers/github
        service_account: ${{ secrets.SERVICE_ACCOUNT_KEY }} #parse the value of repository secret called SERVICE_ACCOUNT_KEY that we have created earlier
        project_id: ${{ env.PROJECT_ID }} #parse the value of env called PROJECT_ID.
    
    - name: build the Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG:  v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG 




#https://medium.com/@ardhanyoga/automating-docker-image-push-to-github-packages-github-container-registry-ghcr-and-google-3ffea20f595b      